# Commit these config files!
# Don't run --help, as it exits the entire application.
# Don't run the same stage twice.

# The processing type that will be used for every stage: local or hpc.
# May be overwritten by a stage's configuration.
processing_type: hpc

# Whether to use the previous output folder as the input folder for the next stage.
# `input_folder` may be overwritten by a stage's configuration.
input_from_previous_output: true

# The output folder template that determines the output folder for every stage.
# May be overwritten by a stage's configuration. If not set, the stage's default
# value will be used.
# Dynamic values that can be used:
#   {pipeline_iteration} is pipeline{run_idx}_{yaml_filename}_{previous_commit_shorthash} and must be the entire folder name.
#   {stage_idx} is the stage 1-based index.
#   {stage_idx0} is the stage 0-based index.
#   {stage_name} is the stage name.
output_folder_template: /projects/prjs0986/wp12/curated/kpn/{pipeline_iteration}/stage{stage_idx}_{stage_name}

# The logs folder used for any stage's Datatrove logs.
# May be overwritten by a stage's configuration. All substrings of
# `{output_folder}` will be replaced by the output folder of the stage, but only
# if `output_folder` is explicitly set (using the stage's `output_folder` option
# or using the global `output_folder_template`).
logs_folder: "{output_folder}/logs"

# The slurm logs folder used for any stage's Datatrove logs.
# May be overwritten by a stage's configuration.
# All substrings of`{output_folder}` will be replaced by the output folder of
# the stage, but only if `output_folder` is explicitly set (using the stage's
# `output_folder` option or using the global `output_folder_template`).
slurm_logs_folder: "{output_folder}/slurm_logs"

# When running the slurm pipeline, one might want to get some updates of a long running process
# without checking the slurm environment everytime with squeue or other tools.
# An alternative is to make use of the Slurm mailing functionality that send the user with the status
# of the running process everytime the status changes.
mail_type: "ALL"
mail_user: ""

# When running a pipeline on HPC, the Energy Aware Runtime (EAR)  system software for energy management can be activated.
# EAR offers energy and performance node monitoring, job accounting and energy optimization.
hpc_ear: "false"

# This argument makes sure that a certain node is not used by the curation pipeline team as the training team is using them for training purposes
hpc_exclude: "gcn[73-74]"

# The stage-dependent options.
# Run `poetry run stage STAGE_NAME` to see the available options per stage.
# Use full option names (e.g. `--input_folder` but without the `--`) instead of
# abbreviations (e.g. `-i`).
# All substrings of `{output_folder}` will be replaced by the output folder of
# the stage, but only if `output_folder` is explicitly set (using the stage's
# `output_folder` option or using the global `output_folder_template`).
# Other substrings are replaced as described for `output_folder_template`.
stages:
  - stage: "string_normalization"
    input_folder: "/projects/prjs0986/wp12/extracted/kpn"
    hpc_n_tasks: "2"
    hpc_time: "00:15:00"
    hpc_partition: "genoa"
    FTFYFormatter:
      normalization: "NFC"
  - stage: "heuristic_filtering"
    hpc_n_tasks: "2"
    hpc_time: "01:00:00"
    hpc_partition: "genoa"
    LanguageFilter:
      languages: [
          "en", # English
          "nl", # Dutch
          "da", # Danish
          "sv", # Swedish
          "af", # Afrikaans
          "fy", # Frisian
          "de", # German
        ]
      language_threshold: "0.65"
      backend: "ft176"
    NordicPileQualityFilter:
      max_digit_fraction: "0.2"
      min_n_char: "50"
      min_mean_med_char: "9"
      min_mean_med_word: "2.1"
    GopherQualityFilter:
      min_doc_words: "null"
      max_doc_words: "null"
      min_avg_word_length: "null"
      max_avg_word_length: "null"
      max_symbol_word_ratio: "0.1"
      max_bullet_lines_ratio: "0.9"
      max_ellipsis_lines_ratio: "null"
      max_non_alpha_words_ratio: "0.8"
      min_stop_words: "2"
    GopherRepetitionFilter:
      dup_line_frac: "0.35"
      dup_para_frac: "0.35"
      dup_line_char_frac: "0.2"
      dup_para_char_frac: "0.2"
      top_n_grams: [[2, 0.25], [3, 0.23], [4, 0.21]]
      dup_n_grams:
        [[5, 0.20], [6, 0.19], [7, 0.18], [8, 0.17], [9, 0.16], [10, 0.15]]
  - stage: toxic_language_detection
    hpc_partition: gpu_h100
    hpc_reservation: gpt-nl
    hpc_gpu: "1"
    hpc_time: "01:00:00" # should take max 4.86h
    hpc_cpus_per_task: "4" # h100: 1/4 node = 16 cores + 1 GPU + 180 GiB
    hpc_mem_per_cpu_gb: "15"
    hpc_n_tasks: "4"
  - stage: pii_masking
    hpc_time: "1:00:00"
    hpc_partition: gpu_a100
    hpc_gpus: "1"
    hpc_cpus_per_task: "16" # Need 16 cores (per private AI GPU instance - actually needs 64 but CPU affinity warnings can be ignored with GPU instance)
    hpc_mem_per_cpu_gb: "4" # Need 64GB ram per private AI instance, 64/16 = 4
    hpc_n_tasks: "4" # Number of data trove tasks with split up files
    # Start multiple containers with different ports and wait for healthy containers
    env_commands: "for gpu in ${{CUDA_VISIBLE_DEVICES//,/ }}; do CUDA_VISIBLE_DEVICES=$gpu apptainer run --nv --contain --pwd /app --env PAI_PORT=$((gpu+SLURM_ARRAY_TASK_ID+8080)) --env PAI_TRITON_HTTP_PORT=$((gpu+SLURM_ARRAY_TASK_ID+SLURM_ARRAY_TASK_MAX+8089)) /projects/0/prjs0986/wp13/private-ai/private_ai_gpu.sif & done; sleep 40"
    PII_PrivateAI_TNO:
      chunk_pool_workers: 32 # Number of workers for chunks
      doc_pool_workers: 16 # Number of workers for documents
      request_batch_size: 64 # Chunks of the same document to be sent in the same request to PAI
      batch_size: 16 # Documents to handle in the same batch
      api_endpoint: "http://localhost:808{CUDA_VISIBLE_DEVICES}/" # Template for endpoint per GPU instance (uses task array index and comma-separated indexes from CUDA_VISIBLE_DEVICES)
      replacement_type: "MARKER" # GPU instance does not support SYNTHETIC
      synthetic_replacement_chance: 1.00 # Replace 100% of markers with own synthetic data
      synthetic_replacement_locale: "nl-NL" # Depending on the dominant language use : English en-GB, Dutch nl-NL
  - stage: deduplication
    hpc_time: "1:00:00"
    hpc_partition: gpu_a100
    hpc_gpus: "1"
    hpc_cpus_per_task: "16" # Need 16 cores (per private AI GPU instance - actually needs 64 but CPU affinity warnings can be ignored with GPU instance)
    hpc_mem_per_cpu_gb: "4" # Need 64GB ram per private AI instance, 64/16 = 4

