# Commit these config files!
# Don't run --help, as it exits the entire application.
# Don't run the same stage twice.

# The processing type that will be used for every stage: local or hpc.
# May be overwritten by a stage's configuration.
processing_type: hpc

# Whether to use the previous output folder as the input folder for the next stage.
# `input_folder` may be overwritten by a stage's configuration.
input_from_previous_output: true

# The output folder template that determines the output folder for every stage.
# May be overwritten by a stage's configuration. If not set, the stage's default
# value will be used.
# Dynamic values that can be used:
#   {pipeline_iteration} is pipeline{run_idx}_{yaml_filename}_{previous_commit_shorthash} and must be the entire folder name.
#   {stage_idx} is the stage 1-based index.
#   {stage_idx0} is the stage 0-based index.
#   {stage_name} is the stage name.
output_folder_template: /projects/prjs0986/wp12/curated/youtube_commons/{pipeline_iteration}/stage{stage_idx}_{stage_name}

# The logs folder used for any stage's Datatrove logs.
# May be overwritten by a stage's configuration. All substrings of
# `{output_folder}` will be replaced by the output folder of the stage, but only
# if `output_folder` is explicitly set (using the stage's `output_folder` option
# or using the global `output_folder_template`).
logs_folder: "{output_folder}/logs"

# The slurm logs folder used for any stage's Datatrove logs.
# May be overwritten by a stage's configuration.
# All substrings of`{output_folder}` will be replaced by the output folder of
# the stage, but only if `output_folder` is explicitly set (using the stage's
# `output_folder` option or using the global `output_folder_template`).
slurm_logs_folder: "{output_folder}/slurm_logs"

# When running the slurm pipeline, one might want to get some updates of a long running process
# without checking the slurm environment everytime with squeue or other tools.
# An alternative is to make use of the Slurm mailing functionality that send the user with the status
# of the running process everytime the status changes.
mail_type: "ALL"
mail_user: ""

# When running a pipeline on HPC, the Energy Aware Runtime (EAR)  system software for energy management can be activated.
# EAR offers energy and performance node monitoring, job accounting and energy optimization.
hpc_ear: "false"

# This argument makes sure that a certain node is not used by the curation pipeline team as the training team is using them for training purposes
hpc_exclude: "gcn[73-76]"

# The stage-dependent options.
# Run `poetry run stage STAGE_NAME` to see the available options per stage.
# Use full option names (e.g. `--input_folder` but without the `--`) instead of
# abbreviations (e.g. `-i`).
# All substrings of `{output_folder}` will be replaced by the output folder of
# the stage, but only if `output_folder` is explicitly set (using the stage's
# `output_folder` option or using the global `output_folder_template`).
# Other substrings are replaced as described for `output_folder_template`.
stages:
  # initial data splitting to parallelize a bit normalization and deduplication signature
  # - stage: "data_splitting"
  #   input_folder: /projects/prjs0986/wp12/extracted/youtube-commons
  #   hpc_n_tasks: 1
  #   hpc_time: "05:00:00"
  #   hpc_partition: "gpu_h100"
  #   hpc_reservation: "gpt-nl"
  #   hpc_gpu: 1
  #   hpc_mem_per_cpu_gb: 8
  #   # normalize
  # - stage: string_normalization
  #   hpc_n_tasks: 20
  #   hpc_time: "10:00:00"
  #   hpc_partition: gpu_h100
  #   hpc_reservation: gpt-nl
  #   hpc_gpu: 1
  #   FTFYFormatter:
  #     normalization: "NFC"
  #   # deduplication before translation
  # - stage: "deduplication"
  #   hpc_n_tasks: 20
  #   hpc_partition: "gpu_h100"
  #   hpc_reservation: "gpt-nl"
  #   hpc_time: "50:00:00"
  #   hpc_mem_per_cpu_gb: 8
  #   hpc_gpu: 1
  #   # split to parallelize translation (from 50 of deduplication) and split lines too long (unbalanced split)
  # - stage: data_splitting
  #   max_file_size: "5_000_000" # 5-6MB
  #   line_chunk_size: 100_000 # split very long lines to reduce variation in compute time for MT
  #   batch_size: 5 # write output files with this frequency to have a margin of 0.1MB
  #   hpc_n_tasks: 20
  #   # hpc_partition: rome # rome or genoa
  #   # hpc_cpus_per_task: 16
  #   # hpc_mem_per_cpu_gb: 1 # needs around 4GB of RAM
  #   hpc_partition: gpu_h100
  #   hpc_reservation: gpt-nl
  #   hpc_gpu: 1 # 1 GPU for each job, faster processing than multi-device
  #   hpc_cpus_per_task: 16  # h100: 1/4 node = 16 cores + 1 GPU + 180 GiB
  #   hpc_mem_per_cpu_gb: 11  # h100: 1/4 node = 180 GiB across 16 cores --> 180/16 = 11.25 GB
  #   hpc_time: "01:00:00" # takes around 1h on gpu_h100
  # - stage: machine_translation
  #   input_folder: /projects/prjs0986/wp12/curated/youtube-commons/pipeline00001_youtube-commons_e1bb716/stage4_data_splitting
  #   output_folder: /projects/prjs0986/wp12/curated/youtube-commons/pipeline00001_youtube-commons_e1bb716/stage5_machine_translation
  #   hpc_n_tasks: 7226 # "7226" # one task for each file
  #   hpc_time: "03:00:00" # should take max 1h
  #   hpc_partition: gpu_h100
  #   hpc_reservation: gpt-nl
  #   hpc_gpu: 1 # 1 GPU for each job, faster processing than multi-device
  #   hpc_cpus_per_task: 16  # h100: 1/4 node = 16 cores + 1 GPU + 180 GiB
  #   hpc_mem_per_cpu_gb: 11  # h100: 1/4 node = 180 GiB across 16 cores --> 180/16 = 11.25 GB
  #   ExtraFieldFilter:
  #     extra_field_name: original_language
  #     # only translate germanic (not dutch), spanish and french
  #     allowed_values: [en, de, lb, af, fy, yi, sco, da, sv, "no", is, fo, es, fr]
  #   # RegexFormatter:
  #   #   pattern: ['\b(\w+)\s+\1\s+\1(\s+\1)*\b', '\s?\[[a-zA-Z&;_à-üÀ-Ü\s]{0,15}\]'] # TODO: doesn't work from yaml, double escapes
  #   TranslatorStep:
  #     # gemma parameters (LLM)
  #     # model_name: ModelSpace/GemmaX2-28-9B-v0.1
  #     # source_language: English # provide it with Gemma (otherwise quality will be very bad)
  #     env_commands: "export HF_HOME=/projects/prjs0986/.hf_cache_dir" # add this to avoid errors
  #     # env_commands: "export HF_HOME=/projects/prjs0986/.hf_cache_dir ; module load 2024 CUDA/12.6.0 ; export CUDA_HOME=/sw/arch/RHEL9/EB_production/2024/software/CUDA/12.6.0/"
  #     # or madlad parameters (huggingface, non-LLM)
  #     model_name: google/madlad400-10b-mt
  #     use_vllm: false
  #     # common parameters
  #     batch_size: 32 # crashes with 32
  #     chunk_size: 512 # critical parameter for quality
  #     chunk_mode: characters # characters or tokens
  #   PostLanguageFilter:
  #     languages: ["nl"]
  #     language_threshold: 0.5
  - stage: "heuristic_filtering"
    input_folder: /gpfs/work5/0/prjs0986/wp12/curated/youtube-commons/pipeline00001_youtube-commons_e1bb716/stage5_machine_translation
    output_folder: /gpfs/work5/0/prjs0986/wp12/curated/youtube-commons/pipeline00001_youtube-commons_e1bb716/stage6_heuristic_filtering
    hpc_n_tasks: "24"
    hpc_time: "20:00:00" # should take max 4.86h
    hpc_partition: "gpu_h100"
    hpc_mem_per_cpu_gb: "8"
    hpc_reservation: "gpt-nl"
    hpc_gpu: "1"
    LanguageFilter:
      languages: [
          "en", # English
          "nl", # Dutch
          "da", # Danish
          "sv", # Swedish
          "af", # Afrikaans
          "fy", # Frisian
          "de", # German
        ]
      language_threshold: "0.55"
      backend: "ft176"
    NordicPileQualityFilter:
      max_digit_fraction: "0.2"
      min_n_char: "50"
      min_mean_med_char: "9"
      min_mean_med_word: "2.1"
    GopherQualityFilter:
      min_doc_words: "null"
      max_doc_words: "null"
      min_avg_word_length: "null"
      max_avg_word_length: "null"
      max_symbol_word_ratio: "0.1"
      max_bullet_lines_ratio: "0.9"
      max_ellipsis_lines_ratio: "0.3"
      max_non_alpha_words_ratio: "0.7"
      min_stop_words: "2"
    GopherRepetitionFilter:
      dup_line_frac: "0.35"
      dup_para_frac: "0.35"
      dup_line_char_frac: "0.2"
      dup_para_char_frac: "0.2"
      top_n_grams: [[2, 0.25], [3, 0.23], [4, 0.21]]
      dup_n_grams:
        [[5, 0.20], [6, 0.19], [7, 0.18], [8, 0.17], [9, 0.16], [10, 0.15]]
  - stage: toxic_language_detection
    input_folder: /gpfs/work5/0/prjs0986/wp12/curated/youtube-commons/pipeline00001_youtube-commons_e1bb716/stage6_heuristic_filtering
    output_folder: /gpfs/work5/0/prjs0986/wp12/curated/youtube-commons/pipeline00001_youtube-commons_e1bb716/stage7_toxic_language_detection
    hpc_partition: gpu_h100
    hpc_reservation: gpt-nl
    hpc_gpu: "1"
    hpc_time: "36:00:00" # should take max 4.86h
    hpc_cpus_per_task: "4" # h100: 1/4 node = 16 cores + 1 GPU + 180 GiB
    hpc_mem_per_cpu_gb: "4"
    hpc_n_tasks: "24"
  # - stage: "deduplication"
  #   hpc_n_tasks: "10"
  #   hpc_partition: "gpu_h100"
  #   hpc_reservation: "gpt-nl"
  #   hpc_time: "01:00:00" # should take max 4.86h
  #   hpc_mem_per_cpu_gb: "8"
  #   hpc_gpu: "1"
  - stage: pii_masking
    input_folder: /gpfs/work5/0/prjs0986/wp12/curated/youtube-commons/pipeline00001_youtube-commons_e1bb716/stage7_toxic_language_detection
    output_folder: /gpfs/work5/0/prjs0986/wp12/curated/youtube-commons/pipeline00001_youtube-commons_e1bb716/stage8_pii_masking
    hpc_time: "18:00:00"
    #hpc_partition: rome #or genoa
    hpc_partition: gpu_h100
    hpc_reservation: gpt-nl
    hpc_gpus: "1"
    hpc_cpus_per_task: "16" # Need 16 cores (per private AI GPU instance - actually needs 64 but CPU affinity warnings can be ignored with GPU instance)
    #hpc_mem_per_cpu_gb: "1"  # 120/128 = 0.9375
    hpc_mem_per_cpu_gb: "6" # Need 64GB ram per private AI instance, 64/16 = 4
    hpc_n_tasks: "8" # Number of data trove tasks with split up files
    # Look into starting multiple containers with different ports and checking their health
    env_commands: "for gpu in ${{CUDA_VISIBLE_DEVICES//,/ }}; do CUDA_VISIBLE_DEVICES=$gpu apptainer run --nv --contain --pwd /app --env PAI_PORT=$((gpu+SLURM_ARRAY_TASK_ID+8080)) --env PAI_TRITON_HTTP_PORT=$((gpu+SLURM_ARRAY_TASK_ID+SLURM_ARRAY_TASK_MAX+8089)) /projects/0/prjs0986/wp13/private-ai/private_ai_gpu.sif & done; sleep 40"
    PII_PrivateAI_TNO:
      chunk_pool_workers: 32 # Number of workers for chunks
      doc_pool_workers: 16 # Number of workers for documents
      request_batch_size: 64 # Chunks of the same document to be sent in the same request to PAI
      batch_size: 16 # Documents to handle in the same batch
      api_endpoint: "http://localhost:808{CUDA_VISIBLE_DEVICES}/" # Template for endpoint per GPU instance (only comma-separated indexes from CUDA_VISIBLE_DEVICES recognized for now), try to go to 8 instances
      replacement_type: "MARKER" # GPU instance does not support SYNTHETIC
      synthetic_replacement_chance: 1.00
      synthetic_replacement_locale: "en-GB" # Depending on the dominant language use : English en-GB, Dutch nl-NL
